# SPDX-License-Identifier: GPL-3.0-or-later
"""A simulated device for development, tests and a demo deployment, where no iPhone is reachable.

It writes a structurally valid backup (the three plists plus a small SQLite Manifest.db), so the
inventory, retention and UI code paths run exactly as they would against a real backup.
"""

from __future__ import annotations

import json
import os
import plistlib
import sqlite3
import tempfile
import time
from collections.abc import Callable
from dataclasses import replace
from datetime import UTC, datetime
from pathlib import Path

from .. import pairing
from . import ios27
from .base import (
    DeviceSeen,
    EngineError,
    NetcheckStep,
    NotConfirmedError,
    PairingCodeCallback,
    PairingRoute,
    PairUsedCallback,
    Phase,
    Progress,
    ProgressCallback,
    SetupState,
    Transport,
    TransportCallback,
)

DEMO_DEVICES = (
    DeviceSeen("00008110-000A1B2C3D4E5F60", Transport.WIFI, "Demo iPhone", "iPhone15,2", "18.6", paired=True),
    DeviceSeen("00008103-001122334455667A", Transport.WIFI, "Demo iPad", "iPad13,4", "18.6", paired=False),
)

# The demo engine never stores either password (same rule as the real one), so it cannot check
# the old one against anything real. Tests that need a deterministic wrong-old-password path pass
# this exact string as `old`; any other value is accepted, matching real ChangePassword behaviour
# for a correct old password.
DEMO_WRONG_OLD_PASSWORD = "wrong-old-password"  # noqa: S105

# The code a simulated wireless pairing shows. Fixed, because a demo whose code changes on every
# reload cannot be walked through in a test or a demo deployment; the real one is generated by
# pymobiledevice3.
DEMO_PAIRING_CODE = "012345"


class DemoEngine:
    name = "demo"

    def __init__(
        self,
        step_seconds: float = 0.4,
        fail_udids: frozenset[str] = frozenset(),
        unconfirmed_udids: frozenset[str] = frozenset(),
        fixed_hosts: Callable[[], dict[str, str]] | None = None,
        data_dir: Path | None = None,
        not_charging_udids: frozenset[str] = frozenset(),
        os_versions: dict[str, str] | None = None,
    ):
        self._step = step_seconds
        self._fail = fail_udids
        self._unconfirmed = unconfirmed_udids
        # Every paired demo device is "charging" by default, so the default only_when_charging=on
        # policy does not block the demo/sandbox schedule end to end; tests that need to exercise
        # "not charging" pass the udid here.
        self._not_charging = not_charging_udids
        # Puts a demo device on another OS version than the one baked into DEMO_DEVICES, so the
        # iOS 27 wireless entrance can be exercised without adding a third demo device -
        # demo_seed.py unpacks DEMO_DEVICES into exactly two names.
        self._os_versions = dict(os_versions or {})
        # Same shape as Pmd3Engine's fixed_hosts (runtime.py), so make_engine can wire the
        # devices.host column into either engine without a special case for the demo one.
        self._fixed_hosts = fixed_hosts or dict
        # With a data_dir (a demo deployment), state lives in a file on the shared /data volume: the web
        # service and the worker each build their own engine, and the setup wizard's Wi-Fi step
        # runs in the worker while its encryption step runs in the web process, so in-memory sets
        # would never see each other. Records uploaded by the code hand-off land in the same
        # pair-records folder Pmd3Engine reads, and count as paired, as they would for real.
        self._records = data_dir / "pair-records" if data_dir else None
        self._state_file = data_dir / "demo-engine-state.json" if data_dir else None
        # Wi-Fi backups follow pairing in the demo story: only the already-paired device (the
        # phone) starts reachable over Wi-Fi. Encryption is deliberately split the other way -
        # the phone starts encrypted (it already has a finished backup below and in demo_seed),
        # the iPad starts unencrypted - so a demo deployment has one device that walks through
        # the whole setup wizard end to end and one that shows it already complete.
        paired = sorted(d.udid for d in DEMO_DEVICES if d.paired)
        # "wireless" holds the devices paired through the iOS 27 entrance; it starts empty and is
        # read with setdefault below, so a state file written before this key existed (from an
        # earlier demo_seed.py) still loads.
        self._memory = {
            "paired": list(paired),
            "wifi": list(paired),
            "encrypted": list(paired),
            "wireless": [],
        }

    # --- state shared between the web and worker processes --------------------------------------

    def _load(self) -> dict[str, list[str]]:
        if self._state_file is None or not self._state_file.is_file():
            return {k: list(v) for k, v in self._memory.items()}
        return json.loads(self._state_file.read_text())

    def _add(self, key: str, udid: str) -> None:
        state = self._load()
        entries = state.setdefault(key, [])
        if udid not in entries:
            entries.append(udid)
        if self._state_file is None:
            self._memory = state
            return
        fd, tmp = tempfile.mkstemp(dir=self._state_file.parent, prefix=".demo-state-")
        with os.fdopen(fd, "w") as fh:
            json.dump(state, fh)
        os.replace(tmp, self._state_file)

    def _has_record(self, udid: str) -> bool:
        if self._records is None:
            return False
        try:
            return pairing.load(self._records, udid) is not None
        except pairing.PairRecordError:
            return False

    def _is_paired(self, udid: str) -> bool:
        return udid in self._load()["paired"] or self._has_record(udid)

    def discover(self, on_pair_used: PairUsedCallback | None = None) -> list[DeviceSeen]:
        # A Wi-Fi entry is only ever paired here through our own stored record (there is no
        # other kind in the demo story), so every paired udid counts as a successful discovery
        # connection - mirrors Pmd3Engine._wifi_lockdowns.
        paired = self._load()["paired"]
        if on_pair_used:
            for udid in paired:
                on_pair_used(udid)
        return [
            DeviceSeen(d.udid, d.transport, d.name, d.product_type, d.os_version, d.udid in paired)
            for d in DEMO_DEVICES
        ]

    def _device(self, udid: str) -> DeviceSeen:
        for d in DEMO_DEVICES:
            if d.udid == udid:
                override = self._os_versions.get(udid)
                return d if override is None else replace(d, os_version=override)
        if self._has_record(udid):
            # A real device paired through the code hand-off: the demo engine cannot reach it, but
            # simulates the rest of the flow so the setup wizard can be walked through end to end.
            return DeviceSeen(udid, Transport.WIFI, "Paired device (simulated)", "iPhone", "unknown", paired=True)
        raise EngineError(f"Device {udid} is not reachable")

    def pair(self, udid: str) -> None:
        self._device(udid)
        self._add("paired", udid)

    # --- the iOS 27 wireless entrance (WirelessPairingEngine, engine/base.py) -------------------

    def pairing_routes(self, udid: str) -> tuple[PairingRoute, ...]:
        """Which entrances this demo device offers. Lockdown is always one of them - a device
        that can pair wirelessly does not lose the path it has."""
        return ios27.routes_for(self._device(udid).os_version)

    def pair_wireless(self, udid: str, on_code: PairingCodeCallback) -> None:
        """Simulate the device-initiated pairing: hand out a six-digit code, then pair.

        Structurally the same as the real flow (bioseasy advertises itself as a pairable host,
        shows a code, the user types it on the device) minus everything that needs a device: no
        mDNS, no Developer Mode, no reboot, no Trust dialog. `route` is recorded so the UI can
        tell the two kinds of pairing apart; the demo engine has no RemotePairing record to
        write, and deliberately does not fake one.
        """
        device = self._device(udid)
        if PairingRoute.REMOTE_PAIRING not in ios27.routes_for(device.os_version):
            raise EngineError(
                f"This device reports iOS {device.os_version or 'unknown'}; pairing without a cable "
                f"needs iOS {ios27.WIRELESS_PAIRING_MIN_MAJOR} or later. Use the helper app instead."
            )
        on_code(DEMO_PAIRING_CODE)
        time.sleep(self._step)
        self._add("paired", udid)
        self._add("wireless", udid)

    def pairing_route(self, udid: str) -> PairingRoute | None:
        """How this device was paired, or None when it is not paired at all."""
        state = self._load()
        if udid in state.get("wireless", []):
            return PairingRoute.REMOTE_PAIRING
        if self._is_paired(udid):
            return PairingRoute.LOCKDOWN
        return None

    def enable_wifi(self, udid: str, on_pair_used: PairUsedCallback | None = None) -> None:
        if not self._is_paired(udid):
            raise EngineError("Pair the device first")
        time.sleep(self._step)
        self._add("wifi", udid)
        if on_pair_used:
            on_pair_used(udid)

    def encryption_enabled(self, udid: str, on_pair_used: PairUsedCallback | None = None) -> bool:
        self._device(udid)
        if self._is_paired(udid) and on_pair_used:
            on_pair_used(udid)
        return udid in self._load()["encrypted"]

    def charging_state(self, udid: str, on_pair_used: PairUsedCallback | None = None) -> bool | None:
        if not self._is_paired(udid):
            return None
        if on_pair_used:
            on_pair_used(udid)
        return udid not in self._not_charging

    def enable_encryption(self, udid: str, password: str) -> None:
        del password  # never stored, even in the demo engine
        if not self._is_paired(udid):
            raise EngineError("Pair the device first")
        time.sleep(self._step)
        self._add("encrypted", udid)

    def change_encryption_password(self, udid: str, old: str, new: str) -> None:
        del new  # never stored, even in the demo engine
        if not self._is_paired(udid):
            raise EngineError("Pair the device first")
        if udid not in self._load()["encrypted"]:
            raise EngineError("Backup encryption is off on this device; turn it on first")
        time.sleep(self._step)
        if old == DEMO_WRONG_OLD_PASSWORD:
            del old
            raise EngineError("The current backup password is not correct")
        del old

    def backup(
        self,
        udid: str,
        target_root: Path,
        on_progress: ProgressCallback,
        on_pair_used: PairUsedCallback | None = None,
        on_transport: TransportCallback | None = None,
    ) -> None:
        device = self._device(udid)
        if not self._is_paired(udid):
            raise EngineError("Device is not paired")
        if udid not in self._load()["encrypted"]:
            # Mirrors Pmd3Engine._backup's own check (get_will_encrypt), so the demo shows why
            # the setup wizard puts encryption before the first backup.
            raise EngineError("Backup encryption is off on this device; turn it on before backing up")
        message = "Enter the passcode on the device"
        host = self._fixed_hosts().get(udid)
        if host:
            message += f" (connecting to {host})"
        on_progress(Progress(Phase.WAITING_FOR_PASSCODE, message=message))
        if on_transport:
            # Every demo device is DeviceSeen(..., Transport.WIFI, ...) - the demo story never
            # simulates a USB-attached device, matching DEMO_DEVICES below.
            on_transport(device.transport)
        time.sleep(self._step)
        if udid in self._unconfirmed:
            raise NotConfirmedError("Nobody confirmed the backup on the device in time")
        # The passcode was confirmed and the (simulated) lockdown session with our stored pair
        # record succeeded - mirrors Pmd3Engine._backup, which reaches TRANSFERRING only once
        # _connect() has returned.
        if on_pair_used:
            on_pair_used(udid)
        for pct in (10, 35, 60, 85, 100):
            if udid in self._fail and pct >= 60:
                raise EngineError("Connection to the device was lost")
            on_progress(Progress(Phase.TRANSFERRING, percent=float(pct)))
            time.sleep(self._step)
        on_progress(Progress(Phase.FINISHING))
        write_backup(target_root / udid, device)

    def detect_setup_state(self, udid: str, on_pair_used: PairUsedCallback | None = None) -> SetupState:
        """Deterministic stand-in for Pmd3Engine._detect_setup_state: an unpaired (unreachable)
        device reports both fields unknown (None), matching "could not confirm"; a paired one
        reports its real membership in the "wifi"/"encrypted" sets, True or False - never None,
        since the demo engine always knows its own state once a device is paired."""
        if not self._is_paired(udid):
            return SetupState(wifi_enabled=None, encryption_enabled=None)
        state = self._load()
        if on_pair_used:
            on_pair_used(udid)
        return SetupState(wifi_enabled=udid in state["wifi"], encryption_enabled=udid in state["encrypted"])

    def netcheck(self, udid: str, on_pair_used: PairUsedCallback | None = None) -> list[NetcheckStep]:
        """Deterministic stand-in for Pmd3Engine._netcheck: same step names and the same "no
        fixed address configured" first step, so the UI and its tests exercise the real
        structure without a device. `fail_udids` (already used by `backup` above to simulate a
        connection dropping mid-transfer) doubles as the deterministic failure case here: a udid
        in that set fails at the first network probe, exactly the "device unreachable at its
        fixed address" case this feature exists to diagnose."""
        self._device(udid)
        if not self._is_paired(udid):
            return [NetcheckStep("Stored pairing", False, "This device is not paired with bioseasy yet.")]
        host = self._fixed_hosts().get(udid)
        if not host:
            return [
                NetcheckStep(
                    "Fixed address configured",
                    False,
                    "No fixed address is set for this device. If it is in a different network "
                    "than bioseasy, set one in the setup wizard or under device settings.",
                )
            ]
        time.sleep(self._step)
        if udid in self._fail:
            return [
                NetcheckStep(
                    "Address reachable (TCP 62078)",
                    False,
                    f"Could not open a TCP connection to {host}:62078 (simulated failure).",
                )
            ]
        if on_pair_used:
            on_pair_used(udid)
        return [
            NetcheckStep("Address reachable (TCP 62078)", True, f"TCP 62078 at {host} accepted a connection"),
            NetcheckStep("Stored pairing", True, "Lockdown accepted the stored pair record"),
            NetcheckStep("Secure session", True, "The TLS session and a lockdown service both work"),
            NetcheckStep("Heartbeat", True, "The device answered Marco/Polo"),
            NetcheckStep("Backup service port reachable (optional)", True, f"TCP port at {host} accepted a connection"),
        ]


def write_backup(path: Path, device: DeviceSeen, *, state: str = "finished", encrypted: bool = True) -> None:
    path.mkdir(parents=True, exist_ok=True)
    now = datetime.now(UTC).replace(tzinfo=None)
    info = {
        "Device Name": device.name,
        "Display Name": device.name,
        "Product Type": device.product_type,
        "Product Version": device.os_version,
        "Serial Number": "DEMO000000",
        "Unique Identifier": device.udid,
        "Target Identifier": device.udid,
        "Last Backup Date": now,
    }
    manifest = {"IsEncrypted": encrypted, "Version": "10.0", "Lockdown": {"UniqueDeviceID": device.udid}}
    status = {"SnapshotState": state, "IsFullBackup": False, "Date": now, "Version": "3.3", "UUID": "DEMO"}
    for name, data in (("Info.plist", info), ("Manifest.plist", manifest), ("Status.plist", status)):
        with (path / name).open("wb") as fh:
            plistlib.dump(data, fh)
    db = path / "Manifest.db"
    db.unlink(missing_ok=True)
    with sqlite3.connect(db) as conn:
        conn.execute("CREATE TABLE Files (fileID TEXT PRIMARY KEY, domain TEXT, relativePath TEXT)")
        conn.execute("INSERT INTO Files VALUES ('0', 'HomeDomain', 'Library/Demo')")
    conn.close()
