-- Frozen schema for bioseasy at SCHEMA_VERSION 8 (src/bioseasy/db.py, SCHEMA string).
-- This is the state of a deployed database before automatic migrations existed.
-- Do not edit this file: it is the fixed baseline tests/test_db_migrate.py migrates
-- from. A schema change belongs in src/bioseasy/db.py's SCHEMA plus a new migration
-- step in MIGRATIONS, never here.

CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    username TEXT NOT NULL UNIQUE COLLATE NOCASE,
    password_hash TEXT,
    role TEXT NOT NULL CHECK (role IN ('admin', 'member')),
    session_version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);
CREATE TABLE devices (
    udid TEXT PRIMARY KEY,
    name TEXT,
    product_type TEXT,
    os_version TEXT,
    owner_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    owner_label TEXT,
    host TEXT,
    interval_hours INTEGER,
    keep_last INTEGER,
    keep_daily INTEGER,
    keep_weekly INTEGER,
    keep_monthly INTEGER,
    keep_yearly INTEGER,
    window_start TEXT,
    window_end TEXT,
    only_when_charging INTEGER,
    overdue_days INTEGER,
    last_nudge_at TEXT,
    last_window_notice_at TEXT,
    name_custom INTEGER NOT NULL DEFAULT 0,
    password_checked_at TEXT,
    password_check_result TEXT CHECK (password_check_result IN ('correct', 'wrong')),
    wifi_enabled_at TEXT,
    encryption_enabled_at TEXT,
    paired_at TEXT,
    pair_used_at TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);
CREATE TABLE runs (
    id INTEGER PRIMARY KEY,
    udid TEXT NOT NULL REFERENCES devices(udid) ON DELETE CASCADE,
    trigger TEXT NOT NULL CHECK (trigger IN ('manual', 'schedule', 'device')),
    started_at TEXT NOT NULL,
    finished_at TEXT,
    status TEXT NOT NULL CHECK (status IN ('running', 'succeeded', 'failed', 'not_confirmed', 'cancelled')),
    message TEXT,
    phase TEXT,
    percent REAL,
    progress_message TEXT,
    worker_id TEXT,
    heartbeat_at TEXT
);
CREATE TABLE sightings (
    udid TEXT NOT NULL REFERENCES devices(udid) ON DELETE CASCADE,
    seen_at TEXT NOT NULL,
    transport TEXT NOT NULL CHECK (transport IN ('usb', 'wifi'))
);
CREATE INDEX sightings_by_device ON sightings (udid, seen_at DESC);
CREATE TABLE ticks (
    tick_at TEXT NOT NULL
);
CREATE INDEX ticks_by_time ON ticks (tick_at);
CREATE INDEX runs_by_device ON runs (udid, started_at DESC);
CREATE UNIQUE INDEX runs_one_running ON runs(udid) WHERE status = 'running';
CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
CREATE TABLE oidc_links (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    issuer TEXT NOT NULL,
    subject TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    PRIMARY KEY (issuer, subject)
);
CREATE INDEX oidc_links_by_user ON oidc_links (user_id);
CREATE TABLE workers (
    id TEXT PRIMARY KEY,
    heartbeat_at TEXT NOT NULL
);
CREATE TABLE seen_devices (
    udid TEXT PRIMARY KEY,
    name TEXT,
    product_type TEXT,
    os_version TEXT,
    transport TEXT NOT NULL CHECK (transport IN ('usb', 'wifi')),
    paired INTEGER NOT NULL DEFAULT 0,
    last_seen_at TEXT NOT NULL
);
CREATE TABLE pairings (
    udid TEXT PRIMARY KEY,
    state TEXT NOT NULL CHECK (state IN ('pending', 'running', 'done', 'failed')),
    message TEXT,
    updated_at TEXT NOT NULL
);
CREATE TABLE setup_actions (
    udid TEXT NOT NULL REFERENCES devices(udid) ON DELETE CASCADE,
    step TEXT NOT NULL CHECK (step IN ('wifi', 'encryption', 'password_change')),
    state TEXT NOT NULL CHECK (state IN ('running', 'done', 'failed')),
    message TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (udid, step)
);
CREATE TABLE api_tokens (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    prefix TEXT NOT NULL UNIQUE,
    secret_hash TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    last_used_at TEXT,
    revoked_at TEXT
);
CREATE INDEX api_tokens_by_user ON api_tokens (user_id);
CREATE TABLE notification_connectors (
    id INTEGER PRIMARY KEY,
    scope TEXT NOT NULL CHECK (scope IN ('device', 'admin')),
    udid TEXT REFERENCES devices(udid) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN ('email', 'telegram', 'apprise')),
    label TEXT NOT NULL,
    settings_json TEXT NOT NULL DEFAULT '{}',
    secret_ciphertext BLOB,
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    CHECK ((scope = 'device') = (udid IS NOT NULL))
);
CREATE INDEX notification_connectors_by_device ON notification_connectors (udid) WHERE scope = 'device';
CREATE INDEX notification_connectors_by_scope ON notification_connectors (scope) WHERE scope = 'admin';
CREATE TABLE pairing_codes (
    id INTEGER PRIMARY KEY,
    code_hash TEXT NOT NULL UNIQUE,
    created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    used_at TEXT,
    consumed_udid TEXT
);
CREATE INDEX pairing_codes_open_by_creator ON pairing_codes (created_by) WHERE used_at IS NULL;

CREATE TABLE netcheck_runs (
    udid TEXT PRIMARY KEY REFERENCES devices(udid) ON DELETE CASCADE,
    state TEXT NOT NULL CHECK (state IN ('running', 'done')),
    steps_json TEXT NOT NULL DEFAULT '[]',
    started_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE dir_sizes (
    path TEXT PRIMARY KEY,
    bytes INTEGER,
    files INTEGER,
    computed_at TEXT,
    state TEXT NOT NULL DEFAULT 'done' CHECK (state IN ('calculating', 'done'))
);
CREATE TABLE activities (
    id TEXT PRIMARY KEY,
    kind TEXT NOT NULL,
    udid TEXT,
    phase TEXT,
    started_at TEXT NOT NULL,
    heartbeat_at TEXT NOT NULL
);
CREATE INDEX activities_by_heartbeat ON activities (heartbeat_at);
INSERT INTO settings (key, value) VALUES ('tick_lease', '1970-01-01T00:00:00Z');
